### Gathering data from csv or tsv

In [1]:
!pip install pandas -q
!pip install requests -q

In [2]:
import pandas as pd

In [3]:
# From Local File
df = pd.read_csv('sample.csv')

In [4]:
df.head()

   ID FirstName LastName                   Email   Department
0   1      John      Doe    john.doe@example.com        Sales
1   2      Jane    Smith  jane.smith@example.com    Marketing
2   3       Bob  Johnson       bob.j@example.com  Engineering

In [5]:
# From URL
df1 = pd.read_csv('https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv')

In [6]:
df1.head()

,John,Doe,120 jefferson st.,Riverside,NJ,08075
0,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
1,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
2,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
3,NaN,Blankman,NaN,SomeTown,SD,298
4,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [7]:
# From Complex URLS
import requests
from io import StringIO

url = "https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df2 = pd.read_csv(data)

In [8]:
df2.head()

,John,Doe,120 jefferson st.,Riverside,NJ,08075
0,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
1,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
2,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
3,NaN,Blankman,NaN,SomeTown,SD,298
4,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

In [9]:
# Reading a TSV File
df3 = pd.read_csv('sample_tsv.tsv')

In [10]:
df3.head()

      0\t50\t5\t881250949
0    0\t172\t5\t881250949
1    0\t133\t1\t881250949
2  196\t242\t3\t881250949
3  186\t302\t3\t891717742
4   22\t377\t1\t878887116

In [11]:
df4 = pd.read_csv('sample_tsv.tsv', sep="\t", names=['n1', 'n2', 'n3', 'n4'])

In [12]:
df4.head()

    n1   n2  n3         n4
0    0   50   5  881250949
1    0  172   5  881250949
2    0  133   1  881250949
3  196  242   3  881250949
4  186  302   3  891717742

### Gathering data from json/sql

### Fetching data from API

### Web Scraping